/* ==========================================================================
   AVALON — Portuguese content
   --------------------------------------------------------------------------
   TRANSLATION PASS NOT DONE. This file is a complete, key-for-key mirror of
   content.en.js with every value replaced by "[PT TRANSLATION PENDING]".
   The EN/PT toggle in the header is fully wired and working — switching to PT
   shows these placeholders, which is the intended state of this build.

   TO TRANSLATE: replace each "[PT TRANSLATION PENDING]" with the Portuguese
   text. Do not rename, add or remove keys — a key missing here falls back to
   English rather than breaking, but the two files should stay in step.

   Generated by tools/generatePortugueseSkeleton.js. Once translation has
   started that script will refuse to overwrite this file.
   ========================================================================== */

window.avalonContent = window.avalonContent || {};

window.avalonContent.pt = {

  brand: {
    wordmark: "[PT TRANSLATION PENDING]",
    footerBlurb: "[PT TRANSLATION PENDING]"
  },

  nav: {
    home: "[PT TRANSLATION PENDING]",
    programs: "[PT TRANSLATION PENDING]",
    house: "[PT TRANSLATION PENDING]",
    admissions: "[PT TRANSLATION PENDING]",
    treatments: "[PT TRANSLATION PENDING]",
    solutions: "[PT TRANSLATION PENDING]",
    family: "[PT TRANSLATION PENDING]",
    familyLong: "[PT TRANSLATION PENDING]",
    about: "[PT TRANSLATION PENDING]",
    waitlist: "[PT TRANSLATION PENDING]",
    openMenu: "[PT TRANSLATION PENDING]",
    closeMenu: "[PT TRANSLATION PENDING]",
    languageLabel: "[PT TRANSLATION PENDING]",
    switchToEnglish: "[PT TRANSLATION PENDING]",
    switchToPortuguese: "[PT TRANSLATION PENDING]",
    skipToContent: "[PT TRANSLATION PENDING]"
  },

  navSub: {
    residence: "[PT TRANSLATION PENDING]",
    dayHospital: "[PT TRANSLATION PENDING]",
    outpatient: "[PT TRANSLATION PENDING]",
    activities: "[PT TRANSLATION PENDING]",
    therapies: "[PT TRANSLATION PENDING]",
    rooms: "[PT TRANSLATION PENDING]",
    commonAreas: "[PT TRANSLATION PENDING]",
    outdoorSpaces: "[PT TRANSLATION PENDING]",
    whySintra: "[PT TRANSLATION PENDING]",
    admissionProcess: "[PT TRANSLATION PENDING]",
    trackProgress: "[PT TRANSLATION PENDING]",
    waitlistForm: "[PT TRANSLATION PENDING]",
    bpd: "[PT TRANSLATION PENDING]",
    bpdLong: "[PT TRANSLATION PENDING]",
    depression: "[PT TRANSLATION PENDING]",
    anxiety: "[PT TRANSLATION PENDING]",
    ptsd: "[PT TRANSLATION PENDING]",
    dbt: "[PT TRANSLATION PENDING]",
    emdr: "[PT TRANSLATION PENDING]",
    mindfulness: "[PT TRANSLATION PENDING]",
    familyResources: "[PT TRANSLATION PENDING]",
    familyAccess: "[PT TRANSLATION PENDING]",
    beliefs: "[PT TRANSLATION PENDING]",
    origin: "[PT TRANSLATION PENDING]",
    medicalTeam: "[PT TRANSLATION PENDING]",
    joinTeam: "[PT TRANSLATION PENDING]"
  },

  cta: {
    eyebrow: "[PT TRANSLATION PENDING]",
    title: "[PT TRANSLATION PENDING]",
    body: "[PT TRANSLATION PENDING]",
    button: "[PT TRANSLATION PENDING]",
    secondary: "[PT TRANSLATION PENDING]",
    aside: "[PT TRANSLATION PENDING]"
  },

  footer: {
    navigateTitle: "[PT TRANSLATION PENDING]",
    programsTitle: "[PT TRANSLATION PENDING]",
    careTitle: "[PT TRANSLATION PENDING]",
    contactTitle: "[PT TRANSLATION PENDING]",
    email: "[PT TRANSLATION PENDING]",
    phone: "[PT TRANSLATION PENDING]",
    address: "[PT TRANSLATION PENDING]",
    legalNote: "[PT TRANSLATION PENDING]",
    copyright: "[PT TRANSLATION PENDING]",
    privacy: "[PT TRANSLATION PENDING]",
    terms: "[PT TRANSLATION PENDING]"
  },

  crisis: {
    title: "[PT TRANSLATION PENDING]",
    body: "[PT TRANSLATION PENDING]"
  },

  forms: {
    labelName: "[PT TRANSLATION PENDING]",
    labelEmail: "[PT TRANSLATION PENDING]",
    labelPhone: "[PT TRANSLATION PENDING]",
    labelRelationship: "[PT TRANSLATION PENDING]",
    labelMessage: "[PT TRANSLATION PENDING]",
    labelSpecialty: "[PT TRANSLATION PENDING]",
    labelNote: "[PT TRANSLATION PENDING]",
    optional: "[PT TRANSLATION PENDING]",
    relationshipDefault: "[PT TRANSLATION PENDING]",
    relationshipSelf: "[PT TRANSLATION PENDING]",
    relationshipFamily: "[PT TRANSLATION PENDING]",
    relationshipClinician: "[PT TRANSLATION PENDING]",
    specialtyDefault: "[PT TRANSLATION PENDING]",
    specialtyPsychiatry: "[PT TRANSLATION PENDING]",
    specialtyPsychology: "[PT TRANSLATION PENDING]",
    specialtyNursing: "[PT TRANSLATION PENDING]",
    specialtyPsychotherapy: "[PT TRANSLATION PENDING]",
    specialtyOther: "[PT TRANSLATION PENDING]",
    submitWaitlist: "[PT TRANSLATION PENDING]",
    submitTeam: "[PT TRANSLATION PENDING]",
    consent: "[PT TRANSLATION PENDING]",
    errorRequired: "[PT TRANSLATION PENDING]",
    errorEmail: "[PT TRANSLATION PENDING]",
    errorSelect: "[PT TRANSLATION PENDING]",
    demoNotice: "[PT TRANSLATION PENDING]",
    waitlistConfirmTitle: "[PT TRANSLATION PENDING]",
    waitlistConfirmBody: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    teamConfirmTitle: "[PT TRANSLATION PENDING]",
    teamConfirmBody: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ]
  },

  home: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    heroCaption: "[PT TRANSLATION PENDING]",
    heroScrollHint: "[PT TRANSLATION PENDING]",
    missionEyebrow: "[PT TRANSLATION PENDING]",
    missionStatement: "[PT TRANSLATION PENDING]",
    introEyebrow: "[PT TRANSLATION PENDING]",
    introTitle: "[PT TRANSLATION PENDING]",
    introParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    introLink: "[PT TRANSLATION PENDING]",
    trustOneLabel: "[PT TRANSLATION PENDING]",
    trustOneText: "[PT TRANSLATION PENDING]",
    trustTwoLabel: "[PT TRANSLATION PENDING]",
    trustTwoText: "[PT TRANSLATION PENDING]",
    trustThreeLabel: "[PT TRANSLATION PENDING]",
    trustThreeText: "[PT TRANSLATION PENDING]",
    exploreEyebrow: "[PT TRANSLATION PENDING]",
    exploreTitle: "[PT TRANSLATION PENDING]",
    exploreLead: "[PT TRANSLATION PENDING]",
    cardProgramsTitle: "[PT TRANSLATION PENDING]",
    cardProgramsText: "[PT TRANSLATION PENDING]",
    cardTreatmentsTitle: "[PT TRANSLATION PENDING]",
    cardTreatmentsText: "[PT TRANSLATION PENDING]",
    cardSolutionsTitle: "[PT TRANSLATION PENDING]",
    cardSolutionsText: "[PT TRANSLATION PENDING]",
    cardHouseTitle: "[PT TRANSLATION PENDING]",
    cardHouseText: "[PT TRANSLATION PENDING]",
    cardFamilyTitle: "[PT TRANSLATION PENDING]",
    cardFamilyText: "[PT TRANSLATION PENDING]",
    cardAdmissionsTitle: "[PT TRANSLATION PENDING]",
    cardAdmissionsText: "[PT TRANSLATION PENDING]",
    cardLinkLabel: "[PT TRANSLATION PENDING]",
    sintraBandEyebrow: "[PT TRANSLATION PENDING]",
    sintraBandTitle: "[PT TRANSLATION PENDING]",
    sintraBandBody: "[PT TRANSLATION PENDING]",
    sintraBandLink: "[PT TRANSLATION PENDING]",
    quoteEyebrow: "[PT TRANSLATION PENDING]",
    quoteText: "[PT TRANSLATION PENDING]",
    quoteAttribution: "[PT TRANSLATION PENDING]",
    aboutEyebrow: "[PT TRANSLATION PENDING]",
    aboutTitle: "[PT TRANSLATION PENDING]",
    aboutBody: "[PT TRANSLATION PENDING]",
    aboutLink: "[PT TRANSLATION PENDING]"
  },

  programs: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    introParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    residenceTitle: "[PT TRANSLATION PENDING]",
    residenceLead: "[PT TRANSLATION PENDING]",
    residenceParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    residencePlaceholder: "[PT TRANSLATION PENDING]",
    dayHospitalTitle: "[PT TRANSLATION PENDING]",
    dayHospitalLead: "[PT TRANSLATION PENDING]",
    dayHospitalParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    dayHospitalPlaceholder: "[PT TRANSLATION PENDING]",
    outpatientTitle: "[PT TRANSLATION PENDING]",
    outpatientLead: "[PT TRANSLATION PENDING]",
    outpatientParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    activitiesTitle: "[PT TRANSLATION PENDING]",
    activitiesLead: "[PT TRANSLATION PENDING]",
    activitiesParagraphs: [
      "[PT TRANSLATION PENDING]"
    ],
    activitiesPlaceholder: "[PT TRANSLATION PENDING]",
    therapiesTitle: "[PT TRANSLATION PENDING]",
    therapiesLead: "[PT TRANSLATION PENDING]",
    therapiesIntro: "[PT TRANSLATION PENDING]",
    therapyIndividualTitle: "[PT TRANSLATION PENDING]",
    therapyIndividualText: "[PT TRANSLATION PENDING]",
    therapySkillsTitle: "[PT TRANSLATION PENDING]",
    therapySkillsText: "[PT TRANSLATION PENDING]",
    moduleMindfulnessTitle: "[PT TRANSLATION PENDING]",
    moduleMindfulnessText: "[PT TRANSLATION PENDING]",
    moduleDistressTitle: "[PT TRANSLATION PENDING]",
    moduleDistressText: "[PT TRANSLATION PENDING]",
    moduleEmotionTitle: "[PT TRANSLATION PENDING]",
    moduleEmotionText: "[PT TRANSLATION PENDING]",
    moduleInterpersonalTitle: "[PT TRANSLATION PENDING]",
    moduleInterpersonalText: "[PT TRANSLATION PENDING]",
    therapyPsychiatryTitle: "[PT TRANSLATION PENDING]",
    therapyPsychiatryText: "[PT TRANSLATION PENDING]",
    therapyConsultTitle: "[PT TRANSLATION PENDING]",
    therapyConsultText: "[PT TRANSLATION PENDING]"
  },

  house: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    heroCaption: "[PT TRANSLATION PENDING]",
    introParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    roomsTitle: "[PT TRANSLATION PENDING]",
    roomsParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    roomsPlaceholder: "[PT TRANSLATION PENDING]",
    roomsMediaNote: "[PT TRANSLATION PENDING]",
    commonAreasTitle: "[PT TRANSLATION PENDING]",
    commonAreasParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    commonAreasPlaceholder: "[PT TRANSLATION PENDING]",
    outdoorTitle: "[PT TRANSLATION PENDING]",
    outdoorLead: "[PT TRANSLATION PENDING]",
    outdoorParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    sintraTitle: "[PT TRANSLATION PENDING]",
    sintraLead: "[PT TRANSLATION PENDING]",
    sintraParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    sintraCaption: "[PT TRANSLATION PENDING]"
  },

  admissions: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    criteriaTitle: "[PT TRANSLATION PENDING]",
    criteriaLead: "[PT TRANSLATION PENDING]",
    criteriaIntro: "[PT TRANSLATION PENDING]",
    criteriaList: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    criteriaNote: "[PT TRANSLATION PENDING]",
    processTitle: "[PT TRANSLATION PENDING]",
    processLead: "[PT TRANSLATION PENDING]",
    processPlaceholder: "[PT TRANSLATION PENDING]",
    stepOneTitle: "[PT TRANSLATION PENDING]",
    stepOneText: "[PT TRANSLATION PENDING]",
    stepTwoTitle: "[PT TRANSLATION PENDING]",
    stepTwoText: "[PT TRANSLATION PENDING]",
    stepThreeTitle: "[PT TRANSLATION PENDING]",
    stepThreeText: "[PT TRANSLATION PENDING]",
    stepFourTitle: "[PT TRANSLATION PENDING]",
    stepFourText: "[PT TRANSLATION PENDING]",
    progressTitle: "[PT TRANSLATION PENDING]",
    progressLead: "[PT TRANSLATION PENDING]",
    progressParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    progressPlaceholder: "[PT TRANSLATION PENDING]",
    waitlistTitle: "[PT TRANSLATION PENDING]",
    waitlistLead: "[PT TRANSLATION PENDING]",
    waitlistParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ]
  },

  treatments: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    introParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    bpdTitle: "[PT TRANSLATION PENDING]",
    bpdLead: "[PT TRANSLATION PENDING]",
    bpdWhatTitle: "[PT TRANSLATION PENDING]",
    bpdWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    bpdSignsTitle: "[PT TRANSLATION PENDING]",
    bpdSignsList: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    bpdMisdiagnosisTitle: "[PT TRANSLATION PENDING]",
    bpdMisdiagnosisParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    bpdWhySpecialistTitle: "[PT TRANSLATION PENDING]",
    bpdWhySpecialistParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    bpdCalloutParagraphs: [
      "[PT TRANSLATION PENDING]"
    ],
    depressionTitle: "[PT TRANSLATION PENDING]",
    depressionLead: "[PT TRANSLATION PENDING]",
    depressionWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    depressionSignsTitle: "[PT TRANSLATION PENDING]",
    depressionSignsList: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    depressionWhyParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    anxietyTitle: "[PT TRANSLATION PENDING]",
    anxietyLead: "[PT TRANSLATION PENDING]",
    anxietyWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    anxietySignsTitle: "[PT TRANSLATION PENDING]",
    anxietySignsList: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    anxietyWhyParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    ptsdTitle: "[PT TRANSLATION PENDING]",
    ptsdLead: "[PT TRANSLATION PENDING]",
    ptsdWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    ptsdSignsTitle: "[PT TRANSLATION PENDING]",
    ptsdSignsList: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    ptsdWhyParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    ptsdLink: "[PT TRANSLATION PENDING]"
  },

  solutions: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    dbtTitle: "[PT TRANSLATION PENDING]",
    dbtLead: "[PT TRANSLATION PENDING]",
    dbtWhatTitle: "[PT TRANSLATION PENDING]",
    dbtWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    dbtModulesTitle: "[PT TRANSLATION PENDING]",
    dbtModulesIntro: "[PT TRANSLATION PENDING]",
    dbtAtAvalonTitle: "[PT TRANSLATION PENDING]",
    dbtAtAvalonParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    dbtAtAvalonPlaceholder: "[PT TRANSLATION PENDING]",
    dbtLink: "[PT TRANSLATION PENDING]",
    emdrTitle: "[PT TRANSLATION PENDING]",
    emdrLead: "[PT TRANSLATION PENDING]",
    emdrWhatParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    emdrAtAvalonTitle: "[PT TRANSLATION PENDING]",
    emdrAtAvalonParagraphs: [
      "[PT TRANSLATION PENDING]"
    ],
    emdrAtAvalonPlaceholder: "[PT TRANSLATION PENDING]",
    mindfulnessTitle: "[PT TRANSLATION PENDING]",
    mindfulnessLead: "[PT TRANSLATION PENDING]",
    mindfulnessParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    mindfulnessPlaceholder: "[PT TRANSLATION PENDING]"
  },

  family: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    introParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    resourcesTitle: "[PT TRANSLATION PENDING]",
    resourcesLead: "[PT TRANSLATION PENDING]",
    resourcesParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    resourcesPlaceholder: "[PT TRANSLATION PENDING]",
    accessTitle: "[PT TRANSLATION PENDING]",
    accessLead: "[PT TRANSLATION PENDING]",
    accessParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    accessPlaceholder: "[PT TRANSLATION PENDING]",
    ctaTitle: "[PT TRANSLATION PENDING]",
    ctaBody: "[PT TRANSLATION PENDING]"
  },

  about: {
    pageTitle: "[PT TRANSLATION PENDING]",
    metaDescription: "[PT TRANSLATION PENDING]",
    heroEyebrow: "[PT TRANSLATION PENDING]",
    heroTitle: "[PT TRANSLATION PENDING]",
    heroLede: "[PT TRANSLATION PENDING]",
    beliefsTitle: "[PT TRANSLATION PENDING]",
    beliefsPlaceholder: "[PT TRANSLATION PENDING]",
    beliefsLead: "[PT TRANSLATION PENDING]",
    beliefOneTitle: "[PT TRANSLATION PENDING]",
    beliefOneText: "[PT TRANSLATION PENDING]",
    beliefTwoTitle: "[PT TRANSLATION PENDING]",
    beliefTwoText: "[PT TRANSLATION PENDING]",
    beliefThreeTitle: "[PT TRANSLATION PENDING]",
    beliefThreeText: "[PT TRANSLATION PENDING]",
    originTitle: "[PT TRANSLATION PENDING]",
    originParagraphs: [
      "[PT TRANSLATION PENDING]"
    ],
    originPlaceholder: "[PT TRANSLATION PENDING]",
    originNote: "[PT TRANSLATION PENDING]",
    teamTitle: "[PT TRANSLATION PENDING]",
    teamLead: "[PT TRANSLATION PENDING]",
    teamParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    teamPlaceholder: "[PT TRANSLATION PENDING]",
    teamCardPhotoLabel: "[PT TRANSLATION PENDING]",
    teamCardNameOne: "[PT TRANSLATION PENDING]",
    teamCardCredentialOne: "[PT TRANSLATION PENDING]",
    teamCardNameTwo: "[PT TRANSLATION PENDING]",
    teamCardCredentialTwo: "[PT TRANSLATION PENDING]",
    teamCardNameThree: "[PT TRANSLATION PENDING]",
    teamCardCredentialThree: "[PT TRANSLATION PENDING]",
    teamCardNameFour: "[PT TRANSLATION PENDING]",
    teamCardCredentialFour: "[PT TRANSLATION PENDING]",
    joinTitle: "[PT TRANSLATION PENDING]",
    joinLead: "[PT TRANSLATION PENDING]",
    joinParagraphs: [
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]",
      "[PT TRANSLATION PENDING]"
    ],
    joinPlaceholder: "[PT TRANSLATION PENDING]"
  },

  media: {
    altHeroTerrace: "[PT TRANSLATION PENDING]",
    altFacade: "[PT TRANSLATION PENDING]",
    altCastleView: "[PT TRANSLATION PENDING]",
    altSalon: "[PT TRANSLATION PENDING]",
    altDiningRoom: "[PT TRANSLATION PENDING]",
    altDiningRoomTwo: "[PT TRANSLATION PENDING]",
    altSittingRoom: "[PT TRANSLATION PENDING]",
    altStaircase: "[PT TRANSLATION PENDING]",
    altCorridor: "[PT TRANSLATION PENDING]",
    altRoomPrincipal: "[PT TRANSLATION PENDING]",
    altRoomMap: "[PT TRANSLATION PENDING]",
    altRoomGuest: "[PT TRANSLATION PENDING]",
    altRoomWindow: "[PT TRANSLATION PENDING]",
    altGardenPath: "[PT TRANSLATION PENDING]",
    altGardenSteps: "[PT TRANSLATION PENDING]",
    altGardenFountain: "[PT TRANSLATION PENDING]",
    altGardenBench: "[PT TRANSLATION PENDING]",
    altGardenVista: "[PT TRANSLATION PENDING]",
    altGardenUndergrowth: "[PT TRANSLATION PENDING]",
    altGardenPavilion: "[PT TRANSLATION PENDING]",
    altGardenWalledPath: "[PT TRANSLATION PENDING]",
    altTerraceUpper: "[PT TRANSLATION PENDING]",
    altSideEntrance: "[PT TRANSLATION PENDING]"
  }
};
