/* ==========================================================================
   Regenerates js/content.pt.js as a key-for-key mirror of js/content.en.js,
   with every value set to the translation placeholder.

   Run:  node tools/generatePortugueseSkeleton.js

   SAFETY: if content.pt.js already contains real translated text, this script
   refuses to run, so a translation pass can never be wiped out by accident.
   Pass --force only if you genuinely mean to discard it.

   Once translation has started, do not use this script. Add new keys to
   content.pt.js by hand instead — `node tools/checkContentKeys.js` will tell
   you which ones are missing.
   ========================================================================== */

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const enPath = path.join(root, 'js/content.en.js');
const ptPath = path.join(root, 'js/content.pt.js');
const TOKEN = '[PT TRANSLATION PENDING]';
const force = process.argv.includes('--force');

if (fs.existsSync(ptPath) && !force) {
  const existing = fs.readFileSync(ptPath, 'utf8');
  const values = existing.match(/: "(?:[^"\\]|\\.)*"/g) || [];
  const translated = values.filter(v => v.indexOf(TOKEN) === -1);
  if (translated.length > 0) {
    console.error(
      'Refusing to overwrite: content.pt.js contains ' + translated.length +
      ' value(s) that are not placeholders.\n' +
      'Translation appears to have started. Add new keys by hand, or pass --force to discard.'
    );
    process.exit(1);
  }
}

global.window = {};
require(enPath);
const en = global.window.avalonContent.en;

function toPlaceholders(value) {
  if (Array.isArray(value)) return value.map(() => TOKEN);
  if (value && typeof value === 'object') {
    const out = {};
    for (const key of Object.keys(value)) out[key] = toPlaceholders(value[key]);
    return out;
  }
  return TOKEN;
}

// Rendered by hand rather than with JSON.stringify so the file stays readable
// and diffable, and matches the shape of content.en.js.
function render(obj, indent) {
  const pad = ' '.repeat(indent);
  const lines = [];

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    if (Array.isArray(value)) {
      lines.push(`${pad}${key}: [`);
      value.forEach((item, i) => lines.push(`${pad}  "${item}"${i < value.length - 1 ? ',' : ''}`));
      lines.push(`${pad}],`);
    } else if (value && typeof value === 'object') {
      lines.push('');
      lines.push(`${pad}${key}: {`);
      lines.push(render(value, indent + 2));
      lines.push(`${pad}},`);
    } else {
      lines.push(`${pad}${key}: "${value}",`);
    }
  }

  // Drop the trailing comma from the last entry at this level.
  for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i].trim() === '') continue;
    lines[i] = lines[i].replace(/,$/, '');
    break;
  }
  return lines.join('\n');
}

const header = `/* ==========================================================================
   AVALON — Portuguese content
   --------------------------------------------------------------------------
   TRANSLATION PASS NOT DONE. This file is a complete, key-for-key mirror of
   content.en.js with every value replaced by "${TOKEN}".
   The EN/PT toggle in the header is fully wired and working — switching to PT
   shows these placeholders, which is the intended state of this build.

   TO TRANSLATE: replace each "${TOKEN}" with the Portuguese
   text. Do not rename, add or remove keys — a key missing here falls back to
   English rather than breaking, but the two files should stay in step.

   Generated by tools/generatePortugueseSkeleton.js. Once translation has
   started that script will refuse to overwrite this file.
   ========================================================================== */

window.avalonContent = window.avalonContent || {};

window.avalonContent.pt = {
`;

fs.writeFileSync(ptPath, header + render(toPlaceholders(en), 2) + '\n};\n', 'utf8');

function countKeys(obj) {
  let total = 0;
  for (const key of Object.keys(obj)) {
    const value = obj[key];
    if (Array.isArray(value)) total += 1;
    else if (value && typeof value === 'object') total += countKeys(value);
    else total += 1;
  }
  return total;
}

console.log('content.pt.js written — ' + countKeys(en) + ' keys mirrored');
